version: "2"  
services:    
  zookeeper:
    container_name: zookeeper   
    image: zookeeper
    privileged: true 
    ports:  
      - "2181:2181"  
    restart: always
    # volumes:  
      # - /etc/localtime:/etc/localtime