version: "2"  
services:    
  nexus3:
    container_name: nexus3   
    image: sonatype/nexus3
#    image: clearent/nexus
    user: root
    privileged: true 
    ports:   
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
    restart: always
    volumes:  
      - ./nexus-data:/nexus-data