version: '2'
services:
   redis:
      image: redis:2.8.17
      container_name: redis
      restart: always   # 如果容器出现异常，则自动重启
      ports:
         - 6379:6379
      command: redis-server --requirepass Magic.cube_exchange_dev  # redis 设置的密码 
      volumes: 
         - /etc/hosts:/etc/hosts
         - ./data:/data
networks:
  default : 
    external:
      name: exc_net          
